Fix map data incorrect filtering + console errors (#59)
Fixes for this console error
```
d3.v6.min.js:2 Error: <circle> attribute r: A negative value is not valid. ("-0.2357836338418866")
```

Changes:
- Field not converted to numerical
- Filter out colleges that don't have both `clustering_college` and `ec_own_ses_college` populated
- Don't default color to 0
- The numerical values were changed b ecause 
- Add "ORANGERED" color as the midpoint value so that it looks more appealing to the eye

The result looks like this
<img width="960" alt="image" src="https://media.github.students.cs.ubc.ca/user/3266/files/73b2a79c-7b0b-48be-a9b0-f2dc8ad182d2">
<img width="960" alt="image" src="https://media.github.students.cs.ubc.ca/user/3266/files/f258b93c-9347-4273-b12f-e78950caf256">


As for the way I got max/min of each attribute, I used this:
```
        console.log(d3.extent(vis.collegeData.map(d => d.clustering_college)))
        console.log(d3.extent(vis.collegeData.map(d => d.ec_own_ses_college)))
        console.log(vis.collegeData.length)
```